### ISSUE TITLE
There's a bug with your sensor

### ISSUE THREAD

**Issue by rhubarbdog** [Gozem/am2320#2]
I've modified am2320.py to read the sensor in an infinite loop and print it before sleeping for 5 seconds.
when you do this the problem eventually occurs OSError : Too many open files. The line before the return in readSensor method from class AM2320 should read [code]posix.close(fd)[/code]

**Comment by Gozem** [comment]
Thanks for the report. I'll see when I find time to fix it.

**Comment by Gozem** [comment]
Merged, thanks.
